---
- hosts: fresh_machine
  become: true
  vars:
  - default_user: mcmoor
  tasks:
  - name: Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} \
        {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: true
  
  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull Docker Repository
    docker_image:
      name: "{{ default_user }}/getting-started"
      source: pull
  
  - name: Run Getting-Started Container
    docker_container:
      name: "getting-started"
      image: "{{ default_user }}/getting-started"
      state: started
      ports: "3000:3000"
      restart_policy: "unless-stopped"
    register: docker_info
